"""empty message

Revision ID: 7f43c3a75080
Revises: 
Create Date: 2024-05-29 21:40:07.486983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f43c3a75080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etrafli1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('title_mini', sa.String(length=100), nullable=False),
    sa.Column('title_mini_2', sa.String(length=100), nullable=False),
    sa.Column('title_mini_3', sa.String(length=100), nullable=False),
    sa.Column('title_mini_4', sa.String(length=100), nullable=False),
    sa.Column('title_mini_5', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('description_2', sa.String(length=50), nullable=False),
    sa.Column('description_3', sa.String(length=50), nullable=False),
    sa.Column('button', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kampaniya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('description_2', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('online',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=False),
    sa.Column('button_1', sa.String(length=50), nullable=False),
    sa.Column('button_2', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sertler',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_kredit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.Column('fin_code', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_kredit')
    op.drop_table('sertler')
    op.drop_table('online')
    op.drop_table('kampaniya')
    op.drop_table('etrafli1')
    # ### end Alembic commands ###
