"""empty message

Revision ID: 9fc996c69111
Revises: d693d50066f9
Create Date: 2024-05-29 16:51:38.310063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9fc996c69111'
down_revision = 'd693d50066f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sans', schema=None) as batch_op:
        batch_op.alter_column('explanation',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sans', schema=None) as batch_op:
        batch_op.alter_column('explanation',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###
