"""empty message

Revision ID: ae653485467e
Revises: 9fc996c69111
Create Date: 2024-05-29 19:38:19.276688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae653485467e'
down_revision = '9fc996c69111'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarif', schema=None) as batch_op:
        batch_op.alter_column('column2',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarif', schema=None) as batch_op:
        batch_op.alter_column('column2',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
